### ISSUE TITLE
`assert_error_sent` for 404s Not Working?

### ISSUE THREAD

**Issue by jherdman** [vt-elixir/ja_resource#72]
I generated a Phoenix 1.3 controller using ja_resource 0.3, and my DELETE test looks like this:

```elixir
  describe "delete source" do
    setup [:create_source]

    test "deletes chosen source", %{conn: conn, source: source} do
      conn = delete conn, source_path(conn, :delete, source)

      assert response(conn, 204)

      assert_error_sent 404, fn ->
        get conn, source_path(conn, :show, source)
      end
    end
 ```

This test is failing:

```
  1) test delete source deletes chosen source (DailyBugleWeb.SourceControllerTest)
     test/daily_bugle_web/controllers/source_controller_test.exs:103
     expected error to be sent as 404 status, but response sent 404 without error
     code: assert_error_sent 404, fn ->
     stacktrace:
       (phoenix) lib/phoenix/test/conn_test.ex:600: Phoenix.ConnTest.assert_error_sent/2
       test/daily_bugle_web/controllers/source_controller_test.exs:108: (test
```

I'm fairly new to Phoenix and Elixir, so I'm not entirely sure what's wrong here. I think the gist is that the subsequent GET request isn't throwing an error. I'd love to pair on a solution as a learning opportunity.

**Comment by jherdman** [comment]
OK, I think I've narrowed down the problem. In `JaResource.Record` [the method used](https://github.com/vt-elixir/ja_resource/blob/9826d24f180df57e65503d3f1b3c9c408717893f/lib/ja_resource/record.ex#L37) to get the record doesn't throw an error. If I override the `handle_show` callback like this:

```elixir
  def handle_show(_, id) do
    Repo.get!(Source, id)
  end
```

Everything works as expected.

**Comment by beerlington** [comment]
Hi @jherdman - this seems to be just something that JaResource is opinionated about. I can't find anything that says the server has to raise an exception when you return a 404. [This comment from Chris Mccord](https://github.com/phoenixframework/phoenix/issues/1577#issuecomment-202191969) makes it sound like there isn't a right or wrong way to do it in Phoenix. I personally just check the status code as Chris suggests, rather than testing explicitly for an exception. I'm happy to reconsider how JaResource handles it though if a case can be made for it.

**Comment by jherdman** [comment]
This was really helpful, thank you for your response. I'm pretty sure I understand what's going on here a lot more now. I consider this issue closed. I think checking the status code is the better way to go as well.
